name: Runner-Cashed
on:
  workflow_dispatch:
  #schedule:
    #- cron: "*/15 * * * *"

jobs:
  build:
    name: windows-latest
    runs-on: windows-latest
    steps:
       
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      
      - name: Restore Cache
        id: cache-downloads
        uses: actions/cache@v4
        with:
          path: downloads
          key: downloads-cache

      - name: Dependiences
        run: pip install -r requirements.txt
              
      - name: Setup
        run: python setup.py

      - name: Delete current Data
        run: |
          echo Waiting 10s ...
          timeout /t 10
          echo Deleting ProgramData folder before restore...
          if exist "C:\ProgramData\BlueStacks_nxt" (
            rmdir /s /q "C:\ProgramData\BlueStacks_nxt"
          )
      
      - name: Restore Cache from cash
        id: cache-data
        uses: actions/cache@v4
        with:
          path: C:\ProgramData\BlueStacks_nxt
          key: bs-data-cache-20250408-084440


      - name: Rusting
        run: |
          start rust.exe
          python login.py

      #- name: Launching
      #  run : python launch.py
      
      - name: Looping .. 
        run : python timer.py

      
      
      #- name: Tasking
      #  run : | 
      #    schtasks /delete /tn "RunnerMachineProvisioner" /f
      #    schtasks /create /tn "taskmy" /tr "${{ github.workspace }}\run.bat" /sc once /st $(powershell -Command "(Get-Date).AddMinutes(1).ToString('HH:mm')") /f
      #    taskkill /IM provisioner.exe /F
      



